language: cpp

compiler:
- g++

before_install:
- echo "before install"
- autoconf --version
- automake --version
- ls
- pwd
- autoreconf --install

script: ./configure && make && make ikev2test

os:
- linux
